// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output of the GitHub adapter for one source file.
 *
 * The domain receives this via `IngestPage` / `IngestOntologyOnly`
 * commands and never sees raw HTTP responses, `octocrab` types, or
 * corpus-specific frontmatter / wikilink syntax. That insulation has been
 * exercised twice: the move from a Logseq graph to an Obsidian vault
 * (ADR-2040), and the move from a remote pull to the local vault source
 * (ADR-2114). Neither changed this value object.
 *
 * The corpus format is specified by `docs/VAULT-corpus-format.md`: YAML
 * frontmatter is the one metadata carrier (ADR-2112). There is no
 * `key:: value` property syntax.
 *
 * `frontmatter_json` and `jsonld_blocks` are deliberately `serde_json::Value`
 * because:
 *
 * - Frontmatter is open-ended: §V2 gives meaning to a fixed set of keys and
 *   preserves every other key verbatim.
 * - JSON-LD blocks must round-trip without loss for the ontology parser.
 *
 * The richer DDD-08 fields (`prose_blocks`, `ontology_blocks`,
 * `outbound_wikilinks`) are domain projections built *from* this raw shape;
 * they belong in the Section 8 parser, not in this cross-boundary contract.
 */
export type ParsedMarkdown = { 
/**
 * Repo-relative path, normalised to forward slashes.
 * (Section 8 calls this `path`; we use `canonical_path` to make the
 * normalisation guarantee explicit at the boundary.)
 */
canonical_path: string, 
/**
 * Raw file body, UTF-8.
 */
raw: string, 
/**
 * Parsed vault frontmatter as a JSON object
 * (`docs/VAULT-corpus-format.md` §V2). Keys preserved verbatim. YAML
 * frontmatter is the only carrier: a `key:: value` line in the body is
 * body text and reaches the domain inside `raw`, not here.
 */
frontmatter_json: Record<string, unknown>, 
/**
 * JSON-LD block bodies, one per block, order preserved — plain `json-ld`
 * code fences in the page body (§V3). Empty once the corpus is
 * frontmatter-only (ADR-2112) and `vault_core::parse_page` supersedes the
 * fence parser.
 */
jsonld_blocks: Array<Record<string, unknown>>, 
/**
 * Git blob SHA1 (40 hex chars). Used by the SHA1-gated sync.
 */
commit_sha: string, };
